---
- name: Install blackbox exporter and node exporter
  hosts: exporters
  become: true
  become_method: sudo
  vars:
    action: "setup_exporters"
  tasks:
    - name: "Include jbt.panoptes"
      include_role:
        name: "panoptes"

- name: Install Prometheus
  hosts: monitoring
  become: true
  become_method: sudo
  vars:
    action: "setup_prometheus"
  tasks:
    - name: "Include jbt.panoptes"
      include_role:
        name: "panoptes"

- name: Install Grafana
  hosts: monitoring
  become: true
  become_method: sudo
  vars:
    action: "setup_grafana"
  tasks:
    - name: "Include jbt.panoptes"
      include_role:
        name: "panoptes"
