version: '3'

services:
  blackbox_exporter:
    image: prom/blackbox-exporter:latest
    container_name: blackbox_exporter
    ports:
      - "9115:9115"
    volumes:
      - '../config-files/blackbox:/etc/blackbox:ro'
    restart: unless-stopped
    command:
      - "--config.file=/etc/blackbox/blackbox.yml"

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    hostname: node_exporter
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
