{
 "title": "Blackbox v4",
 "description": "Prometheus Blackbox Exporter Overview",
 "tags": [
  "blackbox",
  "prometheus"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "target",
    "query": {
     "query": "label_values(probe_success, instance)"
    }
   },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(probe_success, job)"
    }
   },
   { "name": "node_exporter_job", "label": "node_exporter_job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  { "title": "General Network Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "SSL Expiry", "gridPos": { "h": 9, "w": 4, "x": 0, "y": 1 } },
  {
   "title": "Exporters UP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job=~'blackbox.*'}) by (job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average DNS Lookup Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds) by (job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average HTTP Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_http_duration_seconds{module=\"http_2xx\",phase=\"connect\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Ping Response Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_icmp_duration_seconds{phase=\"rtt\",module=\"icmp\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Global BlackboxProbe Duration",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum (probe_duration_seconds) by (job)",
     "legendFormat": "{{ instance }} --- {{job}}"
    }
   ]
  },
  {
   "title": "HTTP Response Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_duration_seconds{module=\"http_2xx\"}",
     "legendFormat": "{{job}} > {{ instance }}"
    }
   ]
  },
  {
   "title": "HTTP Success",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "probe_success{module=\"http_2xx\"}",
     "legendFormat": "{{job}} >{{instance}}"
    }
   ]
  },
  {
   "title": "HTTP Latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_http_duration_seconds{phase=\"connect\",module=\"http_2xx\"}",
     "legendFormat": "{{job}} >>> {{instance}}"
    }
   ]
  },
  {
   "title": "Ping Response Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_duration_seconds{module=\"icmp\"}",
     "legendFormat": "{{job}} > {{instance}}"
    }
   ]
  },
  {
   "title": "Ping Success",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "probe_success{module=\"icmp\"}",
     "legendFormat": "{{job}} > {{instance}}"
    }
   ]
  },
  {
   "title": "Ping Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_icmp_duration_seconds{phase=\"rtt\",module=\"icmp\"}",
     "legendFormat": "{{job}} > {{instance}}"
    }
   ]
  },
  {
   "title": "TCP Success",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "probe_success{module=\"tcp_connect\"}",
     "legendFormat": "{{job}} > {{instance}}"
    }
   ]
  },
  {
   "title": "TCP Response Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_duration_seconds{module=\"tcp_connect\"}",
     "legendFormat": "{{job}} > {{instance}}"
    }
   ]
  },
  {
   "title": "SSH Response Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_duration_seconds{module=\"ssh_banner\"}",
     "legendFormat": "{{job}} > {{instance}}"
    }
   ]
  },
  {
   "title": "Sockstat UDP",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_sockstat_UDPLITE_inuse{job=\"$node_exporter_job\"}",
     "legendFormat": "{{instance}} - UDPLITE_inuse - Udplite sockets currently in use"
    },
    {
     "expr": "node_sockstat_UDP_inuse{job=\"$node_exporter_job\"}",
     "legendFormat": "{{instance}} - UDP_inuse - Udp sockets currently in use"
    },
    {
     "expr": "node_sockstat_UDP_mem{job=\"$node_exporter_job\"}",
     "legendFormat": "{{instance}} - UDP_mem - Used memory for udp"
    }
   ]
  },
  {
   "title": "Sockstat Used",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_sockstat_sockets_used{job=\"$node_exporter_job\"}",
     "legendFormat": "{{ instance }} - Sockets used"
    }
   ]
  },
  {
   "title": "Sockstat TCP",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_sockstat_TCP_alloc{job=\"$node_exporter_job\"}",
     "legendFormat": "{{instance}} - TCP_alloc - Allocated sockets"
    },
    {
     "expr": "node_sockstat_TCP_inuse{job=\"$node_exporter_job\"}",
     "legendFormat": "{{instance}} - TCP_inuse - Tcp sockets currently in use"
    },
    {
     "expr": "node_sockstat_TCP_orphan{job=\"$node_exporter_job\"}",
     "legendFormat": "{{instance}} - TCP_orphan - Orphan sockets"
    },
    {
     "expr": "node_sockstat_TCP_tw{job=\"$node_exporter_job\"}",
     "legendFormat": "{{instance}} - TCP_tw - Sockets wating close"
    }
   ]
  },
  {
   "title": "Network Traffic by Packets",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_network_receive_packets_total{job=\"$node_exporter_job\"}[$__rate_interval])) / count by (instance) (node_network_receive_packets_total)",
     "legendFormat": "{{instance}} - {{device}} - Receive"
    },
    {
     "expr": "sum by (instance) (irate(node_network_transmit_packets_total{job=\"$node_exporter_job\"}[$__rate_interval])) / count by (instance) (node_network_transmit_packets_total)",
     "legendFormat": "{{instance}} - {{device}} - Transmit"
    }
   ]
  },
  {
   "title": "TCP Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{job=\"$node_exporter_job\"}",
     "legendFormat": "{{instance}} -  ESTABLISHED or CLOSE- WAIT connections"
    }
   ]
  },
  {
   "title": "Network Traffic Drop",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_network_receive_drop_total{job=\"$node_exporter_job\"}[$__rate_interval]))",
     "legendFormat": "{{instance}} - Receive drop"
    },
    {
     "expr": "sum by (instance) (irate(node_network_transmit_drop_total{job=\"$node_exporter_job\"}[$__rate_interval]))",
     "legendFormat": "{{instance}} - Transmit drop"
    }
   ]
  },
  {
   "title": "TCP In / Out",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_netstat_Tcp_InSegs{job=\"$node_exporter_job\"}[$__rate_interval]))",
     "legendFormat": "InSegs - Segments received, including those received in error. This count includes segments received on currently established connections"
    },
    {
     "expr": "sum by (instance) (irate(node_netstat_Tcp_OutSegs{job=\"$node_exporter_job\"}[$__rate_interval]))",
     "legendFormat": "OutSegs - Segments sent, including those on current connections but excluding those containing only retransmitted octets"
    }
   ]
  },
  {
   "title": "UDP In / Out",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_netstat_Udp_InDatagrams{job=\"$node_exporter_job\"}[$__rate_interval]))",
     "legendFormat": "{{instance}} - UDP received"
    },
    {
     "expr": "sum by (instance) (irate(node_netstat_Udp_OutDatagrams{job=\"$node_exporter_job\"}[$__rate_interval]))",
     "legendFormat": "{{instance}} - UDP sent"
    }
   ]
  },
  { "title": "$job status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 }, "repeat": "job" },
  {
   "title": "SSL Expiry",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (probe_ssl_earliest_cert_expiry{job=\"$job\"} - time()) / count by (instance) (probe_ssl_earliest_cert_expiry{job=\"$job\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Exporters UP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 4, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job=~\"blackbox.*\"}) by (job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average DNS Lookup Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 11, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{job=\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average HTTP Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_http_duration_seconds{module=\"http_2xx\",phase=\"connect\",job=\"$job\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Ping RTT",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_icmp_duration_seconds{phase=\"rtt\",module=\"icmp\",job=\"$job\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Global Probe Duration",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum (probe_duration_seconds) by (job)",
     "legendFormat": "{{ instance }} --- {{job}}"
    }
   ]
  },
  {
   "title": "HTTP Response Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_duration_seconds{module=\"http_2xx\",job=\"$job\"}",
     "legendFormat": "{{job}} > {{ instance }}"
    }
   ]
  },
  {
   "title": "HTTP Success",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 95 },
   "targets": [
    {
     "expr": "probe_success{module=\"http_2xx\",job=\"$job\"}",
     "legendFormat": "{{job}} >{{instance}}"
    }
   ]
  },
  {
   "title": "HTTP Latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_http_duration_seconds{phase=\"connect\",module=\"http_2xx\",job=\"$job\"}",
     "legendFormat": "{{job}} >>> {{instance}}"
    }
   ]
  },
  {
   "title": "Ping Response Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_duration_seconds{module=\"icmp\",job=\"$job\"}",
     "legendFormat": "{{job}} > {{instance}}"
    }
   ]
  },
  {
   "title": "Ping Success",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 106 },
   "targets": [
    {
     "expr": "probe_success{module=\"icmp\",job=\"$job\"}",
     "legendFormat": "{{job}} > {{instance}}"
    }
   ]
  },
  {
   "title": "Ping Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_icmp_duration_seconds{phase=\"rtt\",module=\"icmp\",job=\"$job\"}",
     "legendFormat": "{{job}} > {{instance}}"
    }
   ]
  },
  {
   "title": "TCP Success",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 112 },
   "targets": [
    {
     "expr": "probe_success{module=\"tcp_connect\",job=\"$job\"}",
     "legendFormat": "{{job}} > {{instance}}"
    }
   ]
  },
  {
   "title": "TCP Response Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_duration_seconds{module=\"tcp_connect\",job=\"$job\"}",
     "legendFormat": "{{job}} > {{instance}}"
    }
   ]
  },
  {
   "title": "SSH Response Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_duration_seconds{module=\"ssh_banner\",job=\"$job\"}",
     "legendFormat": "{{job}} > {{instance}}"
    }
   ]
  }
 ]
}