global:

  scrape_interval:     15s # By default, scrape targets every 15 seconds.

scrape_configs:

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.56.101:9100', '192.168.56.103:9100', '192.168.56.104:9100']

#
# Blackbox exporter configuration
#

  - job_name: 'blackbox_node_1'
    scrape_interval: 10s
    metrics_path: /probe
    file_sd_configs:
      - files:
          - '/etc/prometheus/blackbox-targets/*.yml'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [module]
        target_label: __param_module
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.56.101:9115

  - job_name: 'blackbox_node_2'
    scrape_interval: 10s
    metrics_path: /probe
    file_sd_configs:
      - files:
          - '/etc/prometheus/blackbox-targets/*.yml'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [module]
        target_label: __param_module
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.56.103:9115

  - job_name: 'blackbox_node_3'
    scrape_interval: 10s
    metrics_path: /probe
    file_sd_configs:
      - files:
          - '/etc/prometheus/blackbox-targets/*.yml'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [module]
        target_label: __param_module
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.56.104:9115
