---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox


platforms:
  - name: exporter-1
    hostname: exporter-1
    box: generic/ubuntu2204
    memory: 1048
    cpus: 1
    interfaces:
      - network_name: private_network
        type: static
        ip: 192.168.56.111
        auto_config: true
    options:
      append_platform_to_hostname: no

  - name: exporter-2
    hostname: exporter-22
    box: generic/ubuntu2204
    memory: 1048
    cpus: 1
    interfaces:
      - network_name: private_network
        type: static
        ip: 192.168.56.112
        auto_config: true
    options:
      append_platform_to_hostname: no

  - name: exporter-3
    hostname: exporter-3
    box: generic/ubuntu2204
    memory: 1048
    cpus: 1
    interfaces:
      - network_name: private_network
        type: static
        ip: 192.168.56.113
        auto_config: true
    options:
      append_platform_to_hostname: no

provisioner:
  name: ansible
  inventory:
    links:
      hosts: '../../vars/inventory.yml'
verifier:
  name: ansible
